cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/sksamal/990/ns-3-dev/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Tools/c_config.py", line 460, in run_c_code\n    bld.compile()\n  File "/home/sksamal/990/ns-3-dev/.waf-1.7.16-9ca17eb492c97b689870b4ff9db75880/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 34754064: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/home/sksamal/990/ns-3-dev/build/.conf_check_d0a3a3e87346a24a0cb64337d5363d6d/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/libs\', \'-lpython27\']\n'
